application: ks-sqlengine
version: master
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /tester.*
  script: tests.wsgitester.application

libraries:
- name: MySQLdb
  version: "latest"


