application: ks-sqlengine
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: sqlengine_api.APPLICATION
- url: /.*
  script: sqlengine.application

libraries:
- name: MySQLdb
  version: "latest"


# You must include the Endpoints library if you wish to serve an API.
- name: endpoints
  version: 1.0
